[package]
name = "trees"
version = "0.1.0"
authors = ["Noam Ta Shma noam.tashma@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_destructure = "1.0.0"
void = "*"

[lib]
name = "trees"
path = "src/lib.rs"

[[bin]]
name = "trees"
path = "src/bin.rs"