[package]
name = "orchard"
version = "0.1.0"
authors = ["Noam Ta Shma noam.tashma@gmail.com"]
edition = "2018"
keywords = ["interval", "segment", "tree", "BST"]
categories = ["data-structures", "algorithms"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_destructure = "1.0.0"
void = "*"
rand = "*"
recursive_reference = {version = "0.*", path = "../recursive_reference" }
futures = {version = "*", optional = true}
async-recursion = {version = "*", optional = true}

[dev-dependencies]
itertools = "*"
text_io = "*"
tokio = "*"

[lib]
name = "orchard"
path = "src/lib.rs"

[features]
async_union = ["futures", "async-recursion"]
default = ["async_union"]