[package]
name = "orchard"
version = "0.1.0"
authors = ["Noam Ta Shma noam.tashma@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_destructure = "1.0.0"
void = "*"
rand = "*"

[dev-dependencies]
itertools = "*"
text_io = "*"

[lib]
name = "orchard"
path = "src/lib.rs"